server:
  port: 8080

spring:
  application:
    name: BM-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: BM-CORE
              order: 1
              uri: lb://BM-CORE
              predicates:
                - Path=/cn/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
